import stempowerPoster from "../assets/stempower-poster.pdf";
import urvPoster from "../assets/urv-poster.pdf";

const projects = [
  {
    title: "Independent Study",
    description:
      "TBD",
  },
  {
    title: "Business Lending Tool",
    description:
      "Building backend for microlending platform using Supabase, Docker Compose, and LLM API (IN PROGRESS)",
    link: "https://github.com/amandaleesherman/Business-lending-tool",
  },
  {
    title: "AWS Serverless Applications Cybersecurity Research",
    description:
      "Research focused on IAM Least-privilege policy in AWS serverless applications generated by static analysis system and LLM models in STEMPOWER REU",
    link: stempowerPoster,
  },
  {
    title: "HTML file XPIA Prevention",
    description:
      "Extended open-source project PyRIT’s indirect prompt injection capabilities to include indirect PI attacks via websites (HTML) and provided an example notebook for the PyRIT website in OSAP program",
    link: "https://github.com/amandaleesherman/PyRIT",
  },
  {
    title: "Computational Linguistics/NLP Research",
    description:
      "Analyzing sentence syntactic structure using Stanford's Stanza Python library to create training/test dataset for a supervised ML model (IN PROGRESS)",
  },
  {
    title: "Membership Inference Attacks in Federated Learning Research",
    description:
      "Researched membership inference attacks in federated learning and graphed and analyzed benchmark ML datasets in URV program",
    link: urvPoster,
  },
  {
    title: "FuseBloom",
    description:
      "Founded FuseBloom, which placed 12 high schoolers in internships and won 2nd Place in 2023 Minute Pitch entrepreneurship competition",
    link: "https://fusebloom.netlify.app/",
  },
];

function Projects() {
  return (
    <div className="min-h-screen bg-zinc-950 py-20">
      <h2 className="text-5xl font-bold text-center mb-16">
        Projects
      </h2>

      <div className="overflow-x-auto">
        <div className="flex gap-8 px-8 pb-8 w-max">
          {projects.map((project, index) => (
            <div
              key={index}
              className="w-[400px] h-[300px]
                         bg-white/10
                         backdrop-blur-md
                         border border-white/20
                         rounded-2xl
                         p-8
                         hover:scale-105
                         transition"
            >
              <h3 className="text-2xl font-bold mb-4">
                {project.title}
              </h3>

              <p className="text-gray-300">
                {project.description}
              </p>

              <button 
                className="mt-6 px-4 py-2 bg-cyan-500 rounded"
                onClick={() => window.location.href = project.link}
              >
                Learn More
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default Projects;